# Generated by Django 2.1.4 on 2019-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_shopuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=23, verbose_name='возраст'),
            preserve_default=False,
        ),
    ]
